import React, { useState } from 'react';
import { FileText, Copy, Check, Printer, Download } from 'lucide-react';

export default function ReportView({ auditData }) {
  if (!auditData) return null;

  const [copied, setCopied] = useState(false);
  const reportMarkdown = auditData.report_markdown;

  const handleCopy = () => {
    navigator.clipboard.writeText(reportMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="max-w-4xl mx-auto py-8 px-4 sm:px-6 space-y-6">
      
      {/* Action Bar */}
      <div className="flex items-center justify-between border-b border-zinc-200 dark:border-zinc-800 pb-4">
        <div>
          <h2 className="text-lg font-semibold tracking-tight text-zinc-900 dark:text-zinc-100 flex items-center space-x-2">
            <FileText className="w-5 h-5 text-accent" />
            <span>AI Fairness & Model Audit Report</span>
          </h2>
          <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-0.5">
            Automated comprehensive compliance and viva audit report answering 13 standard audit points.
          </p>
        </div>

        <div className="flex items-center space-x-2">
          <button
            onClick={handleCopy}
            className="flex items-center space-x-1.5 px-3 py-1.5 rounded text-xs font-mono border border-zinc-200 dark:border-zinc-800 hover:bg-zinc-100 dark:hover:bg-zinc-800 transition-colors text-zinc-700 dark:text-zinc-300"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied' : 'Copy Markdown'}</span>
          </button>
          <button
            onClick={handlePrint}
            className="flex items-center space-x-1.5 px-3 py-1.5 rounded text-xs font-mono bg-zinc-900 dark:bg-zinc-100 text-white dark:text-zinc-900 hover:opacity-90 transition-opacity"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print Report</span>
          </button>
        </div>
      </div>

      {/* Rendered Clean Report Container */}
      <div className="p-8 rounded-lg border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-[#0f1011] shadow-sm space-y-6 text-zinc-900 dark:text-zinc-100">
        
        {/* Document Header */}
        <div className="border-b border-zinc-200 dark:border-zinc-800 pb-6 space-y-2">
          <div className="flex justify-between items-start">
            <div>
              <span className="text-[11px] font-mono uppercase tracking-widest text-accent">FairLens Compliance & Governance</span>
              <h1 className="text-2xl font-bold tracking-tight text-zinc-900 dark:text-zinc-100 mt-1">
                AI Fairness & Model Audit Report
              </h1>
            </div>
            <span className="text-xs font-mono text-zinc-500">
              {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })}
            </span>
          </div>
          <p className="text-xs text-zinc-500 font-mono">
            Dataset: {auditData.dataset_name} | Target: {auditData.detection.selected_target} | Audited Attributes: {auditData.detection.selected_protected_attributes.join(', ')}
          </p>
        </div>

        {/* Formatted Markdown Content */}
        <div className="prose prose-sm dark:prose-invert max-w-none space-y-4 text-xs sm:text-sm leading-relaxed text-zinc-700 dark:text-zinc-300">
          <pre className="whitespace-pre-wrap font-sans bg-transparent p-0 border-0 text-inherit leading-relaxed">
            {reportMarkdown}
          </pre>
        </div>

        {/* Sign-off footer */}
        <div className="pt-6 border-t border-zinc-200 dark:border-zinc-800 flex justify-between items-center text-[11px] font-mono text-zinc-400">
          <span>Generated by FairLens Autonomous Audit Engine</span>
          <span>College Major Project Demonstration</span>
        </div>

      </div>

    </div>
  );
}
