import React, { useState } from 'react';
import { FileText, Copy, Check, Printer, Download } from 'lucide-react';

export default function ReportView({ auditData, onBackToDatasets }) {
  if (!auditData) return null;

  const [copied, setCopied] = useState(false);
  const reportMarkdown = auditData.report_markdown;

  const handleCopy = () => {
    navigator.clipboard.writeText(reportMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="max-w-4xl mx-auto py-8 px-4 sm:px-6 space-y-6">
      
      {/* Top Action Bar: Back to Datasets */}
      {onBackToDatasets && (
        <div className="flex items-center justify-between pb-3 border-b border-zinc-200 dark:border-zinc-800/80">
          <button
            onClick={onBackToDatasets}
            className="inline-flex items-center space-x-1.5 px-3 py-1.5 rounded-md text-xs font-medium text-zinc-700 dark:text-zinc-300 hover:text-zinc-900 dark:hover:text-zinc-100 border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-[#0f1011] hover:bg-zinc-100 dark:hover:bg-zinc-800/80 transition-colors shadow-sm"
          >
            <span>← Back to Datasets</span>
          </button>
          <span className="text-xs font-mono text-zinc-500 dark:text-zinc-400">
            Active Dataset: <span className="font-semibold text-zinc-800 dark:text-zinc-200">{auditData.dataset_name}</span>
          </span>
        </div>
      )}

      {/* Action Bar */}
      <div className="flex items-center justify-between border-b border-zinc-200 dark:border-zinc-800 pb-4">
        <div>
          <h2 className="text-lg font-semibold tracking-tight text-zinc-900 dark:text-zinc-100 flex items-center space-x-2">
            <FileText className="w-5 h-5 text-accent" />
            <span>AI Fairness & Model Audit Report</span>
          </h2>
          <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-0.5">
            Automated comprehensive compliance and viva audit report covering 10 key audit dimensions.
          </p>
        </div>

        <div className="flex items-center space-x-2">
          <button
            onClick={handleCopy}
            className="flex items-center space-x-1.5 px-3 py-1.5 rounded text-xs font-mono border border-zinc-200 dark:border-zinc-800 hover:bg-zinc-100 dark:hover:bg-zinc-800 transition-colors text-zinc-700 dark:text-zinc-300"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied' : 'Copy Markdown'}</span>
          </button>
          <button
            onClick={handlePrint}
            className="flex items-center space-x-1.5 px-3 py-1.5 rounded text-xs font-mono bg-zinc-900 dark:bg-zinc-100 text-white dark:text-zinc-900 hover:opacity-90 transition-opacity"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print Report</span>
          </button>
        </div>
      </div>

      {/* Rendered Clean Report Container */}
      <div className="p-8 rounded-lg border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-[#0f1011] shadow-sm space-y-6 text-zinc-900 dark:text-zinc-100">
        
        {/* Document Header */}
        <div className="border-b border-zinc-200 dark:border-zinc-800 pb-6 space-y-2">
          <div className="flex justify-between items-start">
            <div>
              <span className="text-[11px] font-mono uppercase tracking-widest text-accent">FairLens Compliance & Governance</span>
              <h1 className="text-2xl font-bold tracking-tight text-zinc-900 dark:text-zinc-100 mt-1">
                AI Fairness & Model Audit Report
              </h1>
            </div>
            <span className="text-xs font-mono text-zinc-500">
              {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })}
            </span>
          </div>
          <p className="text-xs text-zinc-500 font-mono">
            Dataset: {auditData.dataset_name} | Target: {auditData.detection.selected_target} | Audited Attributes: {auditData.detection.selected_protected_attributes.join(', ')}
          </p>
        </div>

        {/* Formatted Semantic Report Content */}
        <div className="space-y-4 text-xs sm:text-sm leading-relaxed text-zinc-700 dark:text-zinc-300">
          {renderMarkdownDocument(reportMarkdown)}
        </div>

        {/* Sign-off footer */}
        <div className="pt-6 border-t border-zinc-200 dark:border-zinc-800 flex justify-between items-center text-[11px] font-mono text-zinc-400">
          <span>Generated by FairLens Autonomous Audit Engine</span>
          <span>College Major Project Demonstration</span>
        </div>

      </div>

    </div>
  );
}

// Helper to render inline markdown (bold **...**, code `...`, italics *...*)
function renderInline(text) {
  if (!text) return null;
  const regex = /(`[^`]+`|\*\*[^*]+\*\*|\*[^*]+\*)/g;
  const parts = text.split(regex);

  return parts.map((part, idx) => {
    if (part.startsWith('`') && part.endsWith('`')) {
      const content = part.slice(1, -1);
      return (
        <code
          key={idx}
          className="font-mono text-[11px] px-1.5 py-0.5 mx-0.5 rounded bg-zinc-100 dark:bg-zinc-800 text-zinc-800 dark:text-zinc-200 border border-zinc-200/80 dark:border-zinc-700/80"
        >
          {content}
        </code>
      );
    }
    if (part.startsWith('**') && part.endsWith('**')) {
      const content = part.slice(2, -2);
      return (
        <strong key={idx} className="font-semibold text-zinc-900 dark:text-zinc-100">
          {content}
        </strong>
      );
    }
    if (part.startsWith('*') && part.endsWith('*')) {
      const content = part.slice(1, -1);
      return (
        <em key={idx} className="italic text-zinc-500 dark:text-zinc-400">
          {content}
        </em>
      );
    }
    return part;
  });
}

// Helper to parse full markdown document into clean semantic React elements
function renderMarkdownDocument(markdownText) {
  if (!markdownText) return null;

  const lines = markdownText.split('\n');
  const elements = [];
  let currentList = [];
  let keyIdx = 0;

  const flushList = () => {
    if (currentList.length > 0) {
      elements.push(
        <ul key={`ul-${keyIdx++}`} className="space-y-1.5 my-2 ml-4 list-disc marker:text-zinc-400 dark:marker:text-zinc-600">
          {currentList.map((item, i) => (
            <li key={i} className="text-xs sm:text-sm leading-relaxed text-zinc-700 dark:text-zinc-300">
              {renderInline(item)}
            </li>
          ))}
        </ul>
      );
      currentList = [];
    }
  };

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i];
    const trimmed = rawLine.trim();

    if (!trimmed) {
      flushList();
      continue;
    }

    // Divider
    if (trimmed === '---') {
      flushList();
      elements.push(
        <hr key={`hr-${keyIdx++}`} className="my-6 border-zinc-200 dark:border-zinc-800" />
      );
      continue;
    }

    // Heading 1 (e.g. # FairLens AI Fairness...)
    if (trimmed.startsWith('# ')) {
      flushList();
      // Skip the main document title as it is already rendered in the Document Header above
      continue;
    }

    // Heading 2 (Section headings e.g. ## 1. Dataset & Profiling)
    if (trimmed.startsWith('## ')) {
      flushList();
      elements.push(
        <h2
          key={`h2-${keyIdx++}`}
          className="text-base sm:text-lg font-semibold tracking-tight text-zinc-900 dark:text-zinc-100 mt-6 mb-3 pt-3 border-t border-zinc-100 dark:border-zinc-800/80"
        >
          {trimmed.slice(3)}
        </h2>
      );
      continue;
    }

    // Heading 3 (Subheadings e.g. ### Baseline Model)
    if (trimmed.startsWith('### ')) {
      flushList();
      elements.push(
        <h3 key={`h3-${keyIdx++}`} className="text-sm font-semibold text-zinc-800 dark:text-zinc-200 mt-4 mb-2">
          {trimmed.slice(4)}
        </h3>
      );
      continue;
    }

    // Bullet List Item (- or *)
    if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      currentList.push(trimmed.slice(2));
      continue;
    }

    // Regular Paragraph
    flushList();
    elements.push(
      <p key={`p-${keyIdx++}`} className="text-xs sm:text-sm leading-relaxed text-zinc-700 dark:text-zinc-300 my-2">
        {renderInline(trimmed)}
      </p>
    );
  }

  flushList();
  return elements;
}
